### ISSUE TITLE
Removal of `product` attribute from CVs

### ISSUE THREAD

**Issue by matthew-mizielinski** [WCRP-CMIP/CMIP6Plus_CVs#45]
The `product` field is not used in the CVs and could be removed.

This is an issue to provide a branch of the CVs for (a) testing changes in CMOR and (b) for eventual update to these CVs

**Comment by durack1** [comment]
Just noting where things have been defined across other projects:

input4MIPs (in table header, updated to `input4MIPs`): https://github.com/PCMDI/input4MIPs-cmor-tables/blob/master/Tables/input4MIPs_Omon.json#L11
obs4MIPs (in table header, unchanged from `model-output`): https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/Tables/obs4MIPs_Omon.json#L11

For input4MIPs the `product` is defined in the [`user_input.json`](https://github.com/PCMDI/amipbcs/blob/1.1.9/CMOR/drive_input4MIPs_bcs.json#L4) which overwrites the table header entry. So we need to ensure that CMOR 3.8.x can deal with `product` being removed from the table header, and it needs to be provided by either project_CVs or user_input.json

ping @matthew-mizielinski @wolfiex @taylor13 @mauzey1

**Comment by mauzey1** [comment]
> So we need to ensure that CMOR 3.8.x can deal with product being removed from the table header, and it needs to be provided by either project_CVs or user_input.json

Will this mean that the `product` attribute will be removed from mip-cmor-tables' headers?

**Comment by durack1** [comment]
@mauzey1 yes, I believe so. Apologies for the whiplash on this `product` discussion, I did not spend the time to think this through, and @taylor13 has noted that it's used to define what the data is, in addition to the project itself.

So the path forward will be to remove this from the table headers, so that table information can be used across projects (without the product being defined). And we'll depend upon either the CVs (in the case of a product consistent dataset) or user_input.json (in the case of a varying product dataset) to define what this is.

We'll likely need a product CVs defined in mip-cmor-tables to capture all valid entries:
`model-output`, `observations`, `reanalysis`, `derived`, ...

**Comment by durack1** [comment]
Just trying to reconnect disparate threads, also see discussion at https://github.com/PCMDI/cmor/issues/723#issuecomment-1912797439
